name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - uses: actions/checkout@v3

      # 2. Configurar Docker Buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Login en DockerHub
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 4. Build y push de la imagen
      - name: Build and Push Docker Image
        run: |
          docker build -t joshuamsaechao/reto-4-arquitectura-kubernetes:${{ github.sha }} .
          docker push joshuamsaechao/reto-4-arquitectura-kubernetes:${{ github.sha }}

      # 5. Desplegar a Kubernetes
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl set image deployment/demo-app demo=joshuamsaechao/reto-4-arquitectura-kubernetes:${{ github.sha }}
